# Generated by Django 4.1.3 on 2023-02-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_id',
        ),
    ]
