# Generated by Django 4.1.3 on 2023-02-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_game_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='new_string',
            field=models.CharField(default='', max_length=6),
        ),
    ]
