# Generated by Django 4.1.3 on 2023-02-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='num',
        ),
    ]
